name: Deploy on PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: greenbone/workflows/.github/workflows/deploy-pypi.yml@main
    steps:
      - name: Build and publish to PyPI
        uses: greenbone/actions/pypi-upload@v3
